# Generated by Django 3.1.1 on 2020-09-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopItem',
            new_name='Storage',
        ),
    ]
