# Generated by Django 3.1.1 on 2020-09-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
