# Generated by Django 3.1.1 on 2020-09-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200920_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='attrs',
        ),
        migrations.AddField(
            model_name='storage',
            name='quantity',
            field=models.IntegerField(default=True),
        ),
    ]
