# Generated by Django 3.1.1 on 2020-09-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200920_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='name',
            new_name='title',
        ),
    ]
