# Generated by Django 3.1.1 on 2020-09-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
