# Generated by Django 3.1.1 on 2020-09-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_storage'),
        ('shop', '0002_order'),
    ]

    operations = [
    ]
