# Generated by Django 3.1.1 on 2020-09-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_merge_20200925_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
